version: '3.3'

services:
  mysql:
    build: ./mysql
    restart: always
    container_name: mysql-container
    ports:
      - "3306:3306"

  redis:
    build: ./redis
    restart: always
    container_name: redis-container
    ports:
      - "6379:6379"